name: Multiclient Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  multiclient-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.6'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make

      - name: Create Downloads directory
        run: mkdir -p ~/Downloads

      - name: Run dataset download
        run: make download_multiclient_dataset

      - name: Run with multiclient setup
        run: make run_multiclient_test

      - name: Wait for multiclient results
        run: |
          echo "Waiting for client_alice and client_bob results directories..."

          for i in {1..60}; do  # wait up to 60 Ã— 5s = 300s
            if [ -d "./results/client_alice" ] && [ -d "./results/client_bob" ]; then
              echo "Both result directories found."
              exit 0
            fi

            echo "Not ready yet... ($i)"
            sleep 5
          done

          echo "Timeout waiting for result directories!"
          exit 1

      - name: Compare results for Alice
        run: CLIENT=alice CLIENT_RESULTS=multiclient_1 make compare_results_multiclient

      - name: Compare results for Bob
        run: CLIENT=bob CLIENT_RESULTS=multiclient_2 make compare_results_multiclient
